### ISSUE TITLE
有些打标没看懂，不知道事否是打标错误

### ISSUE THREAD

**Issue by CQUPTNLP** [shijiebei2009/CEC-Corpus#3]
打标数据中，如e4里面包含有s3,是不是标注错误了，应该是s4。

 @shijiebei2009

**Comment by shijiebei2009** [comment]
@CQUPTNLP 给出具体文件路径

**Comment by CQUPTNLP** [comment]
地震  上海：高层建筑普遍有震感但不会造成危害.xml   e4中有s3和e5中有l4

**Comment by shijiebei2009** [comment]
这个应该是标注错误

**Comment by CQUPTNLP** [comment]
哦，好的，还有，如地震   川西发生地震成都震感强烈.xml  中e6里oid有o6,o7,o8三个值，这种是什么意思

**Comment by shijiebei2009** [comment]
记不清了，咨询下刘炜老师吧。
