### ISSUE TITLE
部分XML文件中的did标签出现错误，导致BIO标注时部分触发词类型标错

### ISSUE THREAD

**Issue by licheng0520** [shijiebei2009/CEC-Corpus#7]
did标签前后标反或者出现相同的did。
![错误](https://user-images.githubusercontent.com/36562831/83343395-59e09380-a32c-11ea-8838-92fa4cf761ff.jpg)

**Comment by shijiebei2009** [comment]
@licheng0520 你好，发现问题可以直接提PR，我这边会merge的
